import './globals.css'
import { Inter } from 'next/font/google'
import { AppProvider } from "@/context/store";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-900">
        <main>
          <AppProvider>
          {children}
          </AppProvider>
        </main>
      </body>
    </html>
  )
}
