'pruebas':
- pruebas/**

'prueba-1':
- pruebas/01-reading-list/**

'prueba-2':
- pruebas/02-bazar-universal/**

'web':
- web/**

'chore':
- .github/**
- .gitignore
- LICENSE
- README.md
- package.json
