GET http://localhost:3000/books

###

GET http://localhost:3000/books/2/pages-average

###

POST http://localhost:3000/books
content-type: application/json

{
    "id": 1,
    "title": "Harry Potter y la gallina partida",
    "chapters": 13,
    "pages": 356
}

###

GET http://localhost:3000/authors

###

POST http://localhost:3000/authors
content-type: application/json

{
    "id": 2,
    "name": "Jorge Luis"
}