export const LIST_NAME = {
    AVAILABLE_BOOKS: 'AVAILABLE_BOOKS',
    BOOKS_SELECTED: 'BOOKS_SELECTED',
    AVAILABLE_BOOKS_TITTLE: 'Libros disponibles',
    BOOKS_SELECTED_TITTLE: 'Lista de Lectura',
}
