export enum BookTypes {
	RELOAD = 'RELOAD',
	LOAD_BOOKS = 'LOAD_BOOKS',
	SELECT_BOOK = 'SELECT_BOOK',
	ADD_TO_FAVORITE = 'ADD_TO_FAVORITE',
	REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES',
	LOAD_GENRES = 'LOAD_GENRES',
	SELECTING_GENRE = 'SELECTING_GENRE',
	SEARCH = 'SEARCH',
}
