import Head from "next/head";
import classes from "@/styles/Home.module.css";
import BookList from "@/components/components/BookList";
import books from "public/books.json";
import { useEffect, useState } from "react";

export default function Home(props) {
  useEffect(() => {
    let modifiedBooks = props.booksD.map((book) => {
      book.book.wish = false;
      return book;
    });
    props.setBooks(modifiedBooks);
  }, []);

  const moveList = (book) => {
    const ISBN = book.ISBN;
    props.setBooks((prevBooks) => {
      const bookIndex = prevBooks.findIndex(
        (bookI) => bookI.book.ISBN === ISBN
      );
      if (bookIndex === -1) {
        return prevBooks; // Return previous state
      }

      const updatedBooks = [...prevBooks];
      const wish = updatedBooks[bookIndex].book.wish;
      updatedBooks[bookIndex].book = {
        ...updatedBooks[bookIndex].book,
        wish: !wish,
      };

      return updatedBooks;
    });
  };

  return (
    <>
      <Head>
        <title>BookShelves</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.container}>
        <section>
          <div>
            {`${
              props.books !== null &&
              props.books.filter((book) => !book.book.wish).length
            } `}
            libros disponibles
          </div>
          <section className={classes.filtros}>
            <div className={classes.filtro}>
              <div>Filtrar por paginas</div>
              <div>slider</div>
            </div>
            <div className={classes.filtro}>
              <div>Filtrar por genero</div>
              <div>combobox</div>
            </div>
          </section>
          <BookList
            books={props.books}
            moveList={moveList}
            type={"available"}
          />
        </section>
        <section>
          <h1>Lista de deseo</h1>
          <BookList books={props.books} moveList={moveList} type={"wish"} />
        </section>
      </div>
    </>
  );
}
export async function getStaticProps() {
  const DUMMY_BOOKS = books.library;
  return {
    props: {
      booksD: DUMMY_BOOKS,
    },
  };
}
