export const ARIA_LABELS = {
  PageLogo: 'Logo de la página',
  GoToHomePage: 'Ir a página principal',
  PageTitle: 'Título de la página',
  AvailableBooksCount: 'Número de libros disponibles',
  ShowReadingList: 'Mostrar lista de lectura',
  ReadingListCount: 'Número de libros en lista de lectura',
  PageHeader: 'Encabezado de la página',
  SearchInput: 'Buscar libros',
  SearchButton: 'Presionar para buscar',
  PagesFilter: 'Filtro de páginas',
  GenreFilter: 'Seleccionar género',
  SearchFilters: 'Filtros de búsqueda',
  AvailableBooksHeader: 'Encabezado de libros disponibles',
  AvailableBookCard: 'Libro disponible',
  BookTitle: 'Titulo de libro disponible',
  AddBookToList: 'Añadir libro a lista',
  RemoveBookFromList: 'Remover libro de la lista',
  BookCover: 'Portada de libro',
  BookAuthor: 'Autor del libro',
  ReadingList: 'Lista de lectura',
  PaginationNavigation: 'Navegación de la paginación',
  PreviousPage: 'Ir a página previa',
  NextPage: 'Ir a página siguiente',
  GoToPage: 'Ir a página',
  CurrentPage: 'Página actual, Página'
}
