export const SELECCIONAR_LIBRO = 'SELECCIONAR_LIBRO';
export const ERROR_LIBRO = 'ERROR_LIBRO';
export const OCULTAR_ERROR = 'OCULTAR_ERROR';
export const OBTENER_LIBRO = 'OBTENER_LIBRO';
export const FILTRAR_AMBOS = 'FILTRAR_AMBOS';
export const ELIMINAR_LISTA = 'ELIMINAR_LISTA';
export const FILTRAR_POR_CATEGORIA = 'FILTRAR_POR_CATEGORIA';
export const FILTRAR_POR_PAGINA = 'FILTRAR_POR_PAGINA';