import Navbar from '@/components/Navbar';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Reading List',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex min-h-screen flex-col md:max-w-screen-md md:mx-auto lg:max-w-screen-lg lg:mx-auto xl:max-w-screen-xl xl:mx-auto'>
        <div className='flex-1 flex flex-col gap-3 md:gap-4 lg:gap-5 xl:gap-6 m-4 md:m-6 lg:m-8 xl:m-10'>
          {/* Navbar */}
          <Navbar />
          {/* Main */}
          <main className='flex-1'>{children}</main>
        </div>
        {/* Popup modal */}
        <section className='absolute inset-0 bg-black bg-opacity-50 flex justify-center items-center'>
          <dialog
            open
            className='fixed bottom-0 animate-fade-up md:animate-fade-left w-full md:right-0 md:w-[460px] md:top-0 md:mr-0 md:h-full p-4 bg-secondary shadow h-2/4 md:rounded-t-none rounded-t-3xl text-white'
          >
            <div className='flex flex-row justify-between items-center'>
              <button>Close</button>
              <h2 className='text-2xl font-medium'>Lista de Lectura</h2>
              <button>Close</button>
            </div>
          </dialog>
        </section>
      </body>
    </html>
  );
}
