import './globals.css'
import { Roboto } from 'next/font/google'

const inter = Roboto({ weight: '400', subsets: ['latin'] })

export const metadata = {
    title: 'Book List App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    )
}
