// Generated by CodiumAI
const books = require('../mocks/books.json')
// import books from './mocks/books.json'

describe('books', () => {
  // Tests that the function returns formatted books
  it('returns book data', () => {
    const { library } = books
    const { book } = library[0]

    expect(library).toBeDefined()
    expect(library.length).toBeGreaterThan(0)
    expect(book).toHaveProperty('title')
    expect(book).toHaveProperty('pages')
    expect(book).toHaveProperty('genre')
    expect(book).toHaveProperty('cover')
    expect(book).toHaveProperty('synopsis')
    expect(book).toHaveProperty('year')
    expect(book).toHaveProperty('ISBN')
    expect(book).toHaveProperty('author')
  })
})
