
const typeReducerBook = {
  "LIST_BOOK": "LIST_BOOK",
  "ERROR_BOOK": "ERROR_BOOK",
  "LOADING_BOOK": "LOADING_BOOK",
  "ADD_BOOK_PENDING": "ADD_BOOK_PENDING",
  "REMOVE_BOOK_PENDING": "REMOVE_BOOK_PENDING",
  "LIST_BOOK_PENDING": "LIST_BOOK_PENDING",
}

export {typeReducerBook}