import './globals.css'
import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const title = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  weight: ['700'],
  variable: '--font-title'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${title.variable}`}>{children}</body>
    </html>
  )
}
